---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: ghaith4
    password: zB6Uz@tCy5BRB9

- name: Tag and push to docker hub
  community.docker.docker_image:
    name: devops
    repository: ghaith4/angular-app:latest
    push: yes
    source: local
